name: magic-maze # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Magical Maze Explorer
summary: Solve enchanted mazes full of mystery.
description: Explore intricate mazes filled with magical puzzles, hidden passages, and unique challenges.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  magic-maze:
    command: bin/magic-maze-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  magic-maze:
    plugin: dump
    source: .
    organize:
      magic-maze-bin: bin/
